version: "0.2"
ignorePaths:
  - archive
  - dist
  - node_modules
dictionaries:
  - en_US
  - softwareTerms
  - bash
  - node
  - npm
  - html
  - css
  - typescript
  - filetypes
words:
  - dtcor
  - lcov
  - nojekyll
  - oscs
  - postversion
  - preinstall
  - preversion
  - totree
ignoreWords:
  - zhengxs
